language: r
cache: packages
os: linux

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntugis/ppa'
    packages:
    - libudunits2-dev
    - libv8-dev
    - libprotobuf-dev
    - libprotoc-dev
    - libproj-dev
    - libgeos-dev
    - libgdal-dev
    - protobuf-compiler
    - valgrind
    - libpq-dev
    - netcdf-bin

r_github_packages:
  - jimhester/covr

bioc_packages:
  - ggtree

jobs:
  include:
    - os: linux
      r: release
      env: R_CODECOV=true
    - os: linux
      r: devel

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov()'; fi

notifications:
  email:
    on_success: never
    on_failure: never
  slack:
    secure: YOxbPBFVAMbDbNc/6tDn5749/qOfJkM+hfTraG9LGstCZC2C4I7rxb3BRkUHphIbFuQiH8BW/L+BKPXkLBL8Hrz4uMMyD3RtMX1A9fZ9WizkHMT4GLCHE011TITiYIeJvv41R7RBuy6rn3RLpID5KeMTTDphIz1TOZdl1zsxqds=

env:
  global:
    - R_CHECK_ARGS="--no-build-vignettes --as-cran"
